### ISSUE TITLE
Shadowtraffic generates a schema type that's incompatible with the Confluent Schema registry when constants are used

### ISSUE THREAD

**Issue by SmithJohnTaylor** [ShadowTraffic/shadowtraffic-examples#4] opened 2024-04-18 19:56 UTC
Not sure if this is a Shadowtraffic issue but...

When defining fields in a generator like, `"FIELD": null`, represented as a CONST and the following error when trying to process the message:
```
Unsupported schema type org.everit.json.schema.ConstSchema
```

**Comment by MichaelDrogalis** [comment] 2024-04-18 20:02
Hey @SmithJohnTaylor. Can you give me an exact config for me to reproduce this with? I *suspect* this is part of the behavior from the serializers themselves, but I can confirm with the config.

**Comment by SmithJohnTaylor** [comment] 2024-04-18 20:04
```
{
    "generators": [
      {
        "topic": "test-topic",
        "key": {
          "_gen": "uuid"
        },
        "value": {
          "op_type": { "_gen": "string", "expr": "U" },
          "before": {
            "COMPANY": { "_gen": "integer", "n": { "_gen": "uniformDistribution", "bounds": [1, 9999] } },
            "JOB_CODE": { "_gen": "string", "expr": "1432" },
            "ACTIVE_FLAG": { "_gen": "string", "expr": "B" },
            "JOB_CLASS": { "_gen": "string", "expr": "S  " }
          },
          "after": {
            "COMPANY": { "_gen": "integer", "n": { "_gen": "uniformDistribution", "bounds": [1, 9999] } },
            "JOB_CODE": { "_gen": "string", "expr": "1432" },
            "JOB_CLASS": { "_gen": "string", "expr": "RMD" },
            "ACTIVE_FLAG": {
              "_gen": "weightedOneOf",
              "choices": [
                { "weight": 3, "value": { "_gen": "string", "expr": "A" } },
                { "weight": 1, "value": null }
              ]
            }
          }
        },
        "localConfigs": {
          "throttle": {
            "ms": {
              "_gen": "uniformDistribution",
              "bounds": [1000, 5000]
            }
          },
          "events": {
            "exactly": 100
          }
        }
      }
    ],
    "connections": {
      "dev-kafka": {
        "kind": "kafka",
        "producerConfigs": {
          "bootstrap.servers": "xxx.confluent.cloud:9092",
          "key.serializer": "org.apache.kafka.common.serialization.StringSerializer",
          "value.serializer": "io.confluent.kafka.serializers.json.KafkaJsonSchemaSerializer",
          "schema.registry.url": "https://xxx.confluent.cloud",
          "security.protocol": "SASL_SSL",
          "sasl.mechanism": "PLAIN",
          "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username='xxx' password='xxx';",
          "basic.auth.credentials.source": "USER_INFO",
          "basic.auth.user.info": "xxx:xxx
        }
      }
    }
  }
  
```

**Comment by MichaelDrogalis** [comment] 2024-04-19 14:53
I wonder if this is a bug in the KafkaJsonSchemaDeserializer class? I'm looking at the schema this produces, and `const` is [a valid schema](https://json-schema.org/understanding-json-schema/reference/const) in the JSON Schema spec.

Can you ask the Schema Registry team if this is intentionally unsupported?

**Comment by SmithJohnTaylor** [comment] 2024-04-19 19:50
You’re correct. Turns out it’s currently unsupported in the
JsonSchemaConverter.

**Comment by MichaelDrogalis** [comment] 2024-04-20 00:45
Aha. Does that mean you're stuck, though? Can you think of anything I can do to provide you a workaround?

**Comment by MichaelDrogalis** [comment] 2024-04-20 00:46
I see Robert's already on it. :) https://github.com/confluentinc/schema-registry/pull/3094

**Comment by MichaelDrogalis** [comment] 2024-07-10 17:24
Closing since this looks fixed in Schema Registry.

**Closed as completed by MichaelDrogalis** 2024-07-10 17:24 UTC
